[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet] #1111111111111111111111111111111111111111 placeholder
synx = "GPigmxNjTAwbz3GyMDgniM4jh55DoBca2QgKRHAL5EL6"
synx-escrow = "7fTKPCxy8EMRft33nPVFWxbGK8qn6wDSWXJjoY3jpMo1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/iri369/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
