[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
synx = "GiWGrEfwScYrTXoTECQR2HbRyCwn5Vu6K1tTbCSXm4x2"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/iri369/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
